'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidade de salvamento automático do My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EnderecoPastaRaizOS() As String
            Get
                Return CType(Me("EnderecoPastaRaizOS"),String)
            End Get
            Set
                Me("EnderecoPastaRaizOS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EnderecoTemplateExcel() As String
            Get
                Return CType(Me("EnderecoTemplateExcel"),String)
            End Get
            Set
                Me("EnderecoTemplateExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ParametroExportarDXF() As String
            Get
                Return CType(Me("ParametroExportarDXF"),String)
            End Get
            Set
                Me("ParametroExportarDXF") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MySqlBancoDados() As String
            Get
                Return CType(Me("MySqlBancoDados"),String)
            End Get
            Set
                Me("MySqlBancoDados") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MysqlEndereco() As String
            Get
                Return CType(Me("MysqlEndereco"),String)
            End Get
            Set
                Me("MysqlEndereco") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MysqlUsuario() As String
            Get
                Return CType(Me("MysqlUsuario"),String)
            End Get
            Set
                Me("MysqlUsuario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MysqlSenha() As String
            Get
                Return CType(Me("MysqlSenha"),String)
            End Get
            Set
                Me("MysqlSenha") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BancoDadosAtivo() As String
            Get
                Return CType(Me("BancoDadosAtivo"),String)
            End Get
            Set
                Me("BancoDadosAtivo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TemplatAlmoxarifadorev01() As String
            Get
                Return CType(Me("TemplatAlmoxarifadorev01"),String)
            End Get
            Set
                Me("TemplatAlmoxarifadorev01") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UsuarioLogado() As String
            Get
                Return CType(Me("UsuarioLogado"),String)
            End Get
            Set
                Me("UsuarioLogado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SenhaUsuarioLogado() As String
            Get
                Return CType(Me("SenhaUsuarioLogado"),String)
            End Get
            Set
                Me("SenhaUsuarioLogado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EnderecoNovoFormatoA3() As String
            Get
                Return CType(Me("EnderecoNovoFormatoA3"),String)
            End Get
            Set
                Me("EnderecoNovoFormatoA3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EnderecoNovoFormatoA4() As String
            Get
                Return CType(Me("EnderecoNovoFormatoA4"),String)
            End Get
            Set
                Me("EnderecoNovoFormatoA4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EnderecoTemplateExcelOrdemServico() As String
            Get
                Return CType(Me("EnderecoTemplateExcelOrdemServico"),String)
            End Get
            Set
                Me("EnderecoTemplateExcelOrdemServico") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EnderecoNovoFormatoA4Deitado() As String
            Get
                Return CType(Me("EnderecoNovoFormatoA4Deitado"),String)
            End Get
            Set
                Me("EnderecoNovoFormatoA4Deitado") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LiberaOSsemMaterial() As String
            Get
                Return CType(Me("LiberaOSsemMaterial"),String)
            End Get
            Set
                Me("LiberaOSsemMaterial") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CaixaDelimitadora() As String
            Get
                Return CType(Me("CaixaDelimitadora"),String)
            End Get
            Set
                Me("CaixaDelimitadora") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property TempoRespostaServidor() As Integer
            Get
                Return CType(Me("TempoRespostaServidor"),Integer)
            End Get
            Set
                Me("TempoRespostaServidor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EnviarEmailLiberacaoOS() As String
            Get
                Return CType(Me("EnviarEmailLiberacaoOS"),String)
            End Get
            Set
                Me("EnviarEmailLiberacaoOS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AtualizaCadastroComLeituraBOM() As String
            Get
                Return CType(Me("AtualizaCadastroComLeituraBOM"),String)
            End Get
            Set
                Me("AtualizaCadastroComLeituraBOM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ArquivoConfiguracaoBancoDados() As String
            Get
                Return CType(Me("ArquivoConfiguracaoBancoDados"),String)
            End Get
            Set
                Me("ArquivoConfiguracaoBancoDados") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SQLServerProtheus() As String
            Get
                Return CType(Me("SQLServerProtheus"),String)
            End Get
            Set
                Me("SQLServerProtheus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EnderecoImagens() As String
            Get
                Return CType(Me("EnderecoImagens"),String)
            End Get
            Set
                Me("EnderecoImagens") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property OrdemColunasDataGridView() As String
            Get
                Return CType(Me("OrdemColunasDataGridView"),String)
            End Get
            Set
                Me("OrdemColunasDataGridView") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MYSQL")>  _
        Public Property TipoConexao() As String
            Get
                Return CType(Me("TipoConexao"),String)
            End Get
            Set
                Me("TipoConexao") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property chkAcabamentoObrigatorio() As String
            Get
                Return CType(Me("chkAcabamentoObrigatorio"),String)
            End Get
            Set
                Me("chkAcabamentoObrigatorio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ProgramaRM() As String
            Get
                Return CType(Me("ProgramaRM"),String)
            End Get
            Set
                Me("ProgramaRM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property TravarEmissaoOS() As String
            Get
                Return CType(Me("TravarEmissaoOS"),String)
            End Get
            Set
                Me("TravarEmissaoOS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PlanilhaModeloOmie() As String
            Get
                Return CType(Me("PlanilhaModeloOmie"),String)
            End Get
            Set
                Me("PlanilhaModeloOmie") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SwLynx_4._1.My.MySettings
            Get
                Return Global.SwLynx_4._1.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
